[project]
name = "assignment"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mlxtend>=0.23.4",
    "notebook>=7.4.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "shap>=0.47.2",
    "wordcloud>=1.9.4",
]
